### ISSUE TITLE
Favourited searches added pre 2019.1 upgrades no longer work

### ISSUE THREAD

**Issue by mrblippy** [openequella/openEQUELLA#1280]
**Describe the bug**
Any favorite searches added before upgrading 2019.1 not result in a 
There is no tree for:/access/searching.do error

Caused by a change to FavouriteSearchServiceImpl.java in https://github.com/openequella/openEQUELLA/commit/e65af9bcf5d3c86c02b9396a9e833bc84333ec53 
Seems strange that this wouldn't have been found in an automated test though

The bit that's tripping it up is the fact that old favorite searches got stored in the database with /access/ at the start of the url, which no longer works. If we made a migration that removed it from existing entries in the favourite_search table we wcould probably get away with not having to do any other code changes

**To Reproduce**

1. Add a search to favorites in a pre 2019.1 oEQ 
2. Upgrade to 2019.1
3. Access the favorited search that you added in step 1

**Stacktrace**
`com.tle.web.sections.SectionsRuntimeException: There is no tree for:/access/searching.do
     at com.tle.web.sections.registry.AbstractSectionsController.createInfo(AbstractSectionsController.java:111)
     at com.tle.web.sections.registry.AbstractSectionsController.createForward(AbstractSectionsController.java:185)
     at com.tle.web.sections.generic.DefaultSectionInfo.createForwardForUri(DefaultSectionInfo.java:533)
     at com.tle.core.favourites.service.FavouriteSearchServiceImpl.executeSearch(FavouriteSearchServiceImpl.java:71)
     at com.tle.web.favourites.searches.SearchFavouritesList.runSearch(SearchFavouritesList.java:111)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:498)
     at com.tle.web.sections.events.js.MethodInvocationEventGenerator$1.fireDirect(MethodInvocationEventGenerator.java:94)
     at com.tle.web.sections.events.AbstractDirectEvent.fire(AbstractDirectEvent.java:86)
     at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:420)
     at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:394)
     at com.tle.web.sections.generic.DefaultSectionInfo.processQueue(DefaultSectionInfo.java:388)
     at com.tle.web.sections.registry.AbstractSectionsController.execute(AbstractSectionsController.java:42)
     at com.tle.web.api.LegacyContentApi.$anonfun$submit$1(LegacyContentApi.scala:407)
     at com.tle.web.api.LegacyContentApi.withTreePath(LegacyContentApi.scala:276)
     at com.tle.web.api.LegacyContentApi.submit(LegacyContentApi.scala:404)
     at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:498)
     at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
     at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:511)
     at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:402)
     at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:366)
     at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:361)
     at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:368)
     at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:340)
     at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:313)
     at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:441)
     at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:231)
     at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:137)
     at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:361)
     at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:140)
     at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:217)
     at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:227)
     at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
     at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
     at com.tle.web.remoting.resteasy.RestEasyServlet.service(RestEasyServlet.java:91)
     at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
     at com.tle.web.dispatcher.ServletDispatcher.dispatch(ServletDispatcher.java:95)
     at com.tle.web.dispatcher.RequestDispatchFilter.doFilter(RequestDispatchFilter.java:91)
     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
     at java.lang.Thread.run(Thread.java:748) `

**Platform:**

- OpenEquella Version: 2019.1
- OS: Windows 10

**Additional context**

**Comment by abidingotter** [comment]
Pretty sure that there is supposed to be a redirection servlet that handles all /access/ URLs...

**Comment by mrblippy** [comment]
> Pretty sure that there is supposed to be a redirection servlet that handles all /access/ URLs...
Yeah, it seems like that's not working properly in the context of favourite searches

**Comment by edalex-ian** [comment]
Oh, so it looks as though this has been fixed and even backported to a few places. @mrblippy , @PenghaiZhang  or @cathfitz are any of the able to confirm that? If so, then can we close?

**Comment by cathfitz** [comment]
Fixed
