### ISSUE TITLE
Attachment View count: Open cursor error on oracle upon saving item with large numbers of attachments

### ISSUE THREAD

**Issue by mrblippy** [openequella/openEQUELLA#1323]
**Describe the bug**
When saving an item with a large number of attachments (a particular client has 160 attachments) the following error is produced.

Not sure if it works on other databases, i haven't tried that yet. Some of this is in simpledba land. But I don't know exactly what is at fault.

`16:47:56,635 ERROR [ItemService] Error performing workflow on item: 8c08cecc-510e-4747-837a-48019dbc7d3a/1
java.sql.SQLException: ORA-00604: error occurred at recursive SQL level 1
ORA-01000: maximum open cursors exceeded
ORA-00604: error occurred at recursive SQL level 1
ORA-01000: maximum open cursors exceeded
ORA-01000: maximum open cursors exceeded

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:445)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:879)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:450)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:207)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:884)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1167)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1289)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3584)
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3628)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1493)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at io.doolse.simpledba.jdbc.JDBCQueries$.$anonfun$prepareAndQuery$default$5$1(JDBCQueries.scala:369)
	at io.doolse.simpledba.jdbc.JDBCQueries$.$anonfun$prepareAndQuery$5(JDBCQueries.scala:382)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:87)
	at cats.effect.internals.IORunLoop$.startCancelable(IORunLoop.scala:41)
	at cats.effect.internals.IOBracket$BracketStart.run(IOBracket.scala:86)
	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:70)
	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:36)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:44)
	at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:72)
	at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:52)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:136)
	at cats.effect.internals.IORunLoop$.start(IORunLoop.scala:34)
	at cats.effect.internals.IOBracket$.$anonfun$apply$1(IOBracket.scala:44)
	at cats.effect.internals.IOBracket$.$anonfun$apply$1$adapted(IOBracket.scala:34)
	at cats.effect.internals.IORunLoop$RestartCallback.start(IORunLoop.scala:341)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:119)
	at cats.effect.internals.IORunLoop$.$anonfun$suspendAsync$1(IORunLoop.scala:251)
	at cats.effect.internals.IORunLoop$.$anonfun$suspendAsync$1$adapted(IORunLoop.scala:250)
	at cats.effect.internals.IORunLoop$RestartCallback.start(IORunLoop.scala:341)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:119)
	at cats.effect.internals.IORunLoop$.start(IORunLoop.scala:34)
	at cats.effect.IO.unsafeRunAsync(IO.scala:258)
	at cats.effect.internals.IOPlatform$.unsafeResync(IOPlatform.scala:38)
	at cats.effect.IO.unsafeRunTimed(IO.scala:325)
	at cats.effect.IO.unsafeRunSync(IO.scala:240)
	at com.tle.core.db.RunWithDB$.executeWithHibernate(RunWithDB.scala:51)
	at com.tle.core.item.ViewCountJavaDao$.getAttachmentViewCount(ViewCountJavaDao.scala:149)
	at com.tle.core.item.ViewCountJavaDao.getAttachmentViewCount(ViewCountJavaDao.scala)
	at com.tle.core.item.helper.AttachmentHelper.load(AttachmentHelper.java:114)
	at com.tle.core.item.helper.AbstractHelper.load(AbstractHelper.java:55)
	at com.tle.core.item.helper.ItemHelper.convertToXml(ItemHelper.java:347)
	at com.tle.core.item.helper.ItemHelper.convertToXml(ItemHelper.java:337)
	at com.tle.core.item.helper.ItemHelper.updateItemFromXml(ItemHelper.java:330)
	at com.tle.core.item.standard.operations.SaveOperation.saveToRepository(SaveOperation.java:190)
	at com.tle.core.item.standard.operations.SaveOperation.execute(SaveOperation.java:138)
	at com.tle.core.item.service.impl.ItemServiceImpl.execute(ItemServiceImpl.java:858)
	at com.tle.core.item.service.impl.ItemServiceImpl.execute(ItemServiceImpl.java:817)
	at com.tle.core.item.service.impl.ItemServiceImpl.runOperation(ItemServiceImpl.java:722)
	at com.tle.core.item.service.impl.ItemServiceImpl$$EnhancerByGuice$$91ca0530.CGLIB$runOperation$17(<generated>)
	at com.tle.core.item.service.impl.ItemServiceImpl$$EnhancerByGuice$$91ca0530$$FastClassByGuice$$18776313.invoke(<generated>)
	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52)
	at com.tle.core.item.service.impl.ItemServiceImpl$$EnhancerByGuice$$91ca0530.runOperation(<generated>)
	at com.tle.core.item.service.impl.ItemServiceImpl.operation(ItemServiceImpl.java:939)
	at com.tle.core.item.service.impl.ItemServiceImpl$$EnhancerByGuice$$91ca0530.CGLIB$operation$11(<generated>)
	at com.tle.core.item.service.impl.ItemServiceImpl$$EnhancerByGuice$$91ca0530$$FastClassByGuice$$18776313.invoke(<generated>)
	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52)
	at com.tle.core.item.service.impl.ItemServiceImpl$$EnhancerByGuice$$91ca0530.operation(<generated>)
	at com.tle.web.wizard.impl.WizardServiceImpl.doSave(WizardServiceImpl.java:224)
	at com.tle.web.wizard.command.SaveDialog.save(SaveDialog.java:209)
	at com.tle.web.wizard.command.Save.execute(Save.java:65)
	at com.tle.web.wizard.section.WizardBodySection.command(WizardBodySection.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.tle.web.sections.events.js.MethodInvocationEventGenerator$1.fireDirect(MethodInvocationEventGenerator.java:94)
	at com.tle.web.sections.events.AbstractDirectEvent.fire(AbstractDirectEvent.java:86)
	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:420)
	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:394)
	at com.tle.web.sections.generic.DefaultSectionInfo.processQueue(DefaultSectionInfo.java:388)
	at com.tle.web.sections.registry.AbstractSectionsController.execute(AbstractSectionsController.java:44)
	at com.tle.web.sections.registry.SectionsServlet.service(SectionsServlet.java:71)
	at com.tle.web.sections.equella.MultipartSectionsServlet.service(MultipartSectionsServlet.java:48)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at com.tle.web.dispatcher.ServletDispatcher.dispatch(ServletDispatcher.java:95)
	at com.tle.web.dispatcher.RequestDispatchFilter.doFilter(RequestDispatchFilter.java:91)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)`

**To Reproduce**

1. Start a contribution wizard
2. Attach a large amount of attachments (not sure what the upper limit is, but 160 will definitely blow it up
3. Save/publish the item

**Platform:**

- OpenEquella Version: 2018.2, 2019.1, 2019.1.1, 2019.2
- Database: Orable 12, 11

**Comment by mrblippy** [comment]
Confirmed the issue does not occur on postgres installs

**Comment by mrblippy** [comment]
@doolse is the fix for list likely to be on the oEQ or simpledba?

**Comment by mrblippy** [comment]
The background indexer also can run into this issue But revoking the VIEW_VIEWCOUNT acl wont work around it, since the background indexer executes task as the internal system user, so can do whatever it wants

**Comment by cathfitz** [comment]
Believe this will no longer be an issue with removal of simple dba
