### ISSUE TITLE
Term editor, adding new term with same name but different case causes issues in SQL Server

### ISSUE THREAD

**Issue by abidingotter** [openequella/openEQUELLA#1352]
**Describe the bug**
The UI allows you to create a term with the same name as an existing term, differing only in case.  Once added, you can no longer add child terms to either term.
The problem is only an issue in SQL Server as it does a case-insensitive match on text.

**To Reproduce**
Use a SQL Server database for your Equella
Add a root term called "A"
Add another root term called "a"
Try to add a child to either term.

**Expected behavior**
You should be blocked from creating another term with the same name.  Ideally it would be enforced in the database.

**Stacktrace**
```
org.springframework.remoting.RemoteInvocationFailureException: Invocation of method [public abstract java.lang.String com.tle.common.taxonomy.terms.RemoteTermService.insertTerm(com.tle.common.taxonomy.Taxonomy,java.lang.String,java.lang.String,int)] failed in HTTP invoker remote service at [http://localhost:8080/reports/invoker/com.tle.common.taxonomy.terms.RemoteTermService.service]; nested exception is com.dytech.edge.exceptions.RuntimeApplicationException: query did not return a unique result: 2
	at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.invoke(HttpInvokerClientInterceptor.java:154)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy12.insertTerm(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.tle.common.applet.client.ClientProxy.invoke(ClientProxy.java:49)
	at com.tle.common.applet.client.ClientProxy.invoke(ClientProxy.java:40)
	at com.sun.proxy.$Proxy13.insertTerm(Unknown Source)
	at com.tle.admin.taxonomy.tool.internal.TermTree.doAddNewNode(TermTree.java:77)
	at com.tle.admin.taxonomy.tool.internal.TermTree.doAddNewNode(TermTree.java:43)
	at com.tle.admin.common.gui.tree.AbstractTreeEditorTree$10.construct(AbstractTreeEditorTree.java:455)
	at com.dytech.gui.workers.AdvancedSwingWorker$3.run(AdvancedSwingWorker.java:106)
	at java.lang.Thread.run(Thread.java:745)
```

**Platform:**

- Database: SQL Server

**Comment by abidingotter** [comment]
There is a unique index on taxonomy + parent term id + value hash, however the hash will be different for different casing.  Could make the hash to be on the lowercase version, but that would break existing taxonomies.
