### ISSUE TITLE
Error when importing institution tgz file

### ISSUE THREAD

**Issue by thanhnv3690** [openequella/openEQUELLA#1404]
I installed the lastest version of openEquella and tried to upload institution but the system showed "Please import a institution file". I checked in tomcat log and it has this error
"22:09:16,312ERRORTomcatLog

```
Servlet.service() for servlet [default] in context with path [/] threw exception java.lang.StringIndexOutOfBoundsException: String index out of range: -1
     at java.lang.String.substring(String.java:1931)
     at com.tle.web.institution.InstitutionFilter.doNormal(InstitutionFilter.java:225)
     at com.tle.web.institution.InstitutionFilter.doFilterInternal(InstitutionFilter.java:174)
     at com.tle.web.core.filter.OncePerRequestFilter.filterRequest(OncePerRequestFilter.java:40)
     at com.tle.web.dispatcher.RequestDispatchFilter.doFilter(RequestDispatchFilter.java:66)
     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:528)
     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:810)
     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
     at java.lang.Thread.run(Thread.java:748)"
```

Please help me

**Comment by edalex-ian** [comment]
Hi there @thanhnv3690 

Just to be sure we're talking about the exact same thing, could you please advise exactly what version you're running?

Also, are you able to provide details of:

* What information you entered for your institution and server; as well as
* Operating system information

**Comment by thanhnv3690** [comment]
Hi
I am using OpenEquella v2019.2. The institution file is Vanilla sample from OpenEquella

**Comment by edalex-ian** [comment]
Heya @mrblippy 

Any chance you could try and replicate this please?

**Comment by mrblippy** [comment]
@thanhnv3690 i just imported the [vanilla institution](https://github.com/equella/equella.github.io/blob/master/guides/6.4VanillaReferenceInstitution.tgz) from openequella.github.io
It allowed me to enter my institution details, and the institution import completed successfully (in openEQUELLA 2019.2)

Could you possibly provide some screenshots or a screen recording of you going through the institution import process?
