### ISSUE TITLE
Tomcat 8.5.51 AJP requires a secret or explicitly turned off the secret

### ISSUE THREAD

**Issue by cbeach47** [openequella/openEQUELLA#1520]
**Describe the bug**
With Tomcat 8.5.51, the AJP connector ( irrespective of `tomcat.useBio` ) will fail to start with the error below.

Quick workaround to allow the connector to startup - hard code `secretRequired` to false.  This should be sufficient as long as the AJP connection is fronted with a web server and not exposed.  Note this is the recommended setup anyways.

```
11:16:00,734 ERROR [TomcatLog] Failed to start connector [Connector[org.apache.coyote.ajp.AjpProtocol-8047]]
org.apache.catalina.LifecycleException: Protocol handler start failed
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1057)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:440)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:766)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:439)
	at com.tle.tomcat.service.impl.TomcatServiceImpl.startup(TomcatServiceImpl.java:224)
	at com.tle.core.application.ApplicationStarter.startRoles(ApplicationStarter.java:87)
	at com.tle.core.application.ApplicationStarter.start(ApplicationStarter.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.tle.core.equella.runner.EQUELLAServer.startServer(EQUELLAServer.java:157)
	at com.tle.core.equella.runner.EQUELLAServer.main(EQUELLAServer.java:84)
Caused by: java.lang.IllegalArgumentException: The AJP Connector is configured with secretRequired="true" but the secret attribute is either null or "". This combination is not valid.
	at org.apache.coyote.ajp.AbstractAjpProtocol.start(AbstractAjpProtocol.java:274)
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1055)
	... 15 more
```

**To Reproduce**
1. Configure `ajp.port` in mandatory-config
2. Optionally, configure `tomcat.useBio` in optional-config
3. Start oEQ

**Expected behavior**
oEQ should start up

**Additional context**
This is related to the dep upgrade https://github.com/openequella/openEQUELLA/pull/1498

**Comment by edalex-ian** [comment]
Sounds good to me to go with a simple "hard code `secretRequired` to false". If there's anything already in the doco about setting up AJP we may want to mention that oEQ with AJP is non-secret secured.
