### ISSUE TITLE
docker-compose database issue

### ISSUE THREAD

**Issue by cbeach47** [openequella/openEQUELLA#1531]
**Describe the bug**
`docker-compose up -d` succeeds, but the logs are throwing an error with the postgre database (below).  Is there something missing from the documentation?

**To Reproduce**
Using docker-compose v 1.25.4 :
Run `docker-compose up -d`
Run `docker-compose logs` and note the errors with the database

**Expected behavior**
docker-compose should start up cleanly without external dependencies.

**Stacktrace**
```
oeq_1        | Caused by: java.net.UnknownHostException: database
oeq_1        | 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
oeq_1        | 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
oeq_1        | 	at java.net.Socket.connect(Socket.java:589)
oeq_1        | 	at org.postgresql.core.PGStream.<init>(PGStream.java:75)
oeq_1        | 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:91)
oeq_1        | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
oeq_1        | 	... 16 more
database_1   | Error: Database is uninitialized and superuser password is not specified.
database_1   |        You must specify POSTGRES_PASSWORD to a non-empty value for the
database_1   |        superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
database_1   | 
database_1   |        You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
database_1   |        connections without a password. This is *not* recommended.
database_1   | 
database_1   |        See PostgreSQL documentation about "trust":
database_1   |        https://www.postgresql.org/docs/current/auth-trust.html

```

**Platform:**

- OpenEquella Version: [2020.1.0-RC4]
- OS: [Ubuntu 16]

**Comment by edalex-ian** [comment]
Heya @PenghaiZhang 

Could you have a look at this please?

Thanks.

**Comment by PenghaiZhang** [comment]
> Heya @PenghaiZhang
> 
> Could you have a look at this please?
> 
> Thanks.

Yeah I will have a look today.

**Comment by PenghaiZhang** [comment]
@cbeach47 , I tried `docker-compose logs | grep "UnknownHostException"` but did not see `java.net.UnknownHostException: database`. 

I wonder if  [this article](http://support.divio.com/en/articles/3719228-database-is-uninitialized-and-superuser-password-is-not-specified) can help.

**Comment by PenghaiZhang** [comment]
Totally removed my database container and spin up again. I just needed to recreate the database and user account. Maybe I need to update my compose version.

**Comment by PenghaiZhang** [comment]
OK after removing Postgres image and pulling the image again, I can reproduce this error.

**Comment by PenghaiZhang** [comment]
The recommended fix is giving environment variable `POSTGRES_PASSWORD` a value.
`    environment:
      POSTGRES_PASSWORD: password
`

**Comment by edalex-ian** [comment]
You can have the compose file pull this value from the host environment. I suggest we do that and go with documentation.

So in the `docker-compose.yml`, rather than doing:

```yaml
environment:
  - POSTGRES_PASSWORD=supersekret
```

You specify it with no value to signify docker compose to read it from the host env vars. E.g.:

```yaml
environment:
  - POSTGRES_PASSWORD
```
