### ISSUE TITLE
Newer versions of SBT fail

### ISSUE THREAD

**Issue by edalex-ian** [openequella/openEQUELLA#1691]
**Describe the bug**

It would appear that currently we can not use any version of SBT greater than 1.1.x. This is unfortunate, as there are some rather nice enhancements in 1.2.x and 1.3.x.

**To Reproduce**

Steps to reproduce the behaviour:

1. Set one of the newer versions in `project/build.properties`
2. Attempt to run: `sbt clean installerZip`

**Expected behaviour**

A build is produced with no errors.

**Stacktrace**

With 1.2.8:

```
[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.jboss.spec.javax.ws.rs#jboss-jaxrs-api_2.1_spec;working@ian-edalex-laptop: not found
[error] unresolved dependency: org.reactivestreams#reactive-streams;working@ian-edalex-laptop: not found
[error] unresolved dependency: javax.validation#validation-api;working@ian-edalex-laptop: not found
[error] unresolved dependency: org.jboss.spec.javax.annotation#jboss-annotations-api_1.2_spec;working@ian-edalex-laptop: not found
[error] unresolved dependency: org.apache.httpcomponents#httpclient;working@ian-edalex-laptop: not found
[error] unresolved dependency: commons-io#commons-io;working@ian-edalex-laptop: not found
[error] unresolved dependency: net.jcip#jcip-annotations;working@ian-edalex-laptop: not found
[error] unresolved dependency: javax.json.bind#javax.json.bind-api;working@ian-edalex-laptop: not found
[error] unresolved dependency: org.jboss.logging#jboss-logging;working@ian-edalex-laptop: not found
[error] unresolved dependency: org.jboss.logging#jboss-logging-annotations;working@ian-edalex-laptop: not found
[error] unresolved dependency: org.jboss.logging#jboss-logging-processor;working@ian-edalex-laptop: not found
[error] unresolved dependency: org.eclipse.microprofile.rest.client#microprofile-rest-client-api;working@ian-edalex-laptop: not found
[error] unresolved dependency: org.eclipse.microprofile.config#microprofile-config-api;working@ian-edalex-laptop: not found
[error] 	at sbt.internal.librarymanagement.ivyint.CachedResolutionResolveEngine.mergeErrors(CachedResolutionResolveEngine.scala:495)
[error] 	at sbt.internal.librarymanagement.ivyint.CachedResolutionResolveEngine.mergeErrors$(CachedResolutionResolveEngine.scala:483)
[error] 	at sbt.internal.librarymanagement.IvySbt$ParallelCachedResolutionResolveEngine.mergeErrors(Ivy.scala:138)
[error] 	at sbt.internal.librarymanagement.ivyint.CachedResolutionResolveEngine.mergeResults(CachedResolutionResolveEngine.scala:480)
[error] 	at sbt.internal.librarymanagement.ivyint.CachedResolutionResolveEngine.mergeResults$(CachedResolutionResolveEngine.scala:471)
[error] 	at sbt.internal.librarymanagement.IvySbt$ParallelCachedResolutionResolveEngine.mergeResults(Ivy.scala:138)
[error] 	at sbt.internal.librarymanagement.ivyint.CachedResolutionResolveEngine.$anonfun$customResolve$1(CachedResolutionResolveEngine.scala:461)
[error] 	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:903)
[error] 	at sbt.internal.librarymanagement.ivyint.CachedResolutionResolveCache.getOrElseUpdateProjectReport(CachedResolutionResolveEngine.scala:310)
[error] 	at sbt.internal.librarymanagement.ivyint.CachedResolutionResolveEngine.customResolve(CachedResolutionResolveEngine.scala:357)
[error] 	at sbt.internal.librarymanagement.ivyint.CachedResolutionResolveEngine.customResolve$(CachedResolutionResolveEngine.scala:346)
[error] 	at sbt.internal.librarymanagement.IvySbt$ParallelCachedResolutionResolveEngine.customResolve(Ivy.scala:138)
[error] 	at sbt.internal.librarymanagement.IvyActions$.cachedResolveAndRetrieve(IvyActions.scala:377)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:207)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:238)
[error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
[error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:45)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:93)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:106)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:106)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:89)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:120)
[error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2561)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (equellaserver / update) sbt.librarymanagement.ResolveException: unresolved dependency: org.jboss.spec.javax.ws.rs#jboss-jaxrs-api_2.1_spec;working@ian-edalex-laptop: not found
[error] unresolved dependency: org.reactivestreams#reactive-streams;working@ian-edalex-laptop: not found
[error] unresolved dependency: javax.validation#validation-api;working@ian-edalex-laptop: not found
[error] unresolved dependency: org.jboss.spec.javax.annotation#jboss-annotations-api_1.2_spec;working@ian-edalex-laptop: not found
[error] unresolved dependency: org.apache.httpcomponents#httpclient;working@ian-edalex-laptop: not found
[error] unresolved dependency: commons-io#commons-io;working@ian-edalex-laptop: not found
[error] unresolved dependency: net.jcip#jcip-annotations;working@ian-edalex-laptop: not found
[error] unresolved dependency: javax.json.bind#javax.json.bind-api;working@ian-edalex-laptop: not found
[error] unresolved dependency: org.jboss.logging#jboss-logging;working@ian-edalex-laptop: not found
[error] unresolved dependency: org.jboss.logging#jboss-logging-annotations;working@ian-edalex-laptop: not found
[error] unresolved dependency: org.jboss.logging#jboss-logging-processor;working@ian-edalex-laptop: not found
[error] unresolved dependency: org.eclipse.microprofile.rest.client#microprofile-rest-client-api;working@ian-edalex-laptop: not found
[error] unresolved dependency: org.eclipse.microprofile.config#microprofile-config-api;working@ian-edalex-laptop: not found
```

With 1.3.10:

```
[error] lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] https://repo1.maven.org/maven2/maven-plugins/maven-cobertura-plugin/1.3/maven-cobertura-plugin-1.3.plugin: not found: https://repo1.maven.org/maven2/maven-plugins/maven-cobertura-plugin/1.3/maven-cobertura-plugin-1.3.plugin
[error] https://repo1.maven.org/maven2/maven-plugins/maven-findbugs-plugin/1.3.1/maven-findbugs-plugin-1.3.1.plugin: not found: https://repo1.maven.org/maven2/maven-plugins/maven-findbugs-plugin/1.3.1/maven-findbugs-plugin-1.3.1.plugin
[error] 
[error] 	at lmcoursier.internal.shaded.coursier.Artifacts$.$anonfun$fetchArtifacts$14(Artifacts.scala:302)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
[error] 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Caused by: lmcoursier.internal.shaded.coursier.cache.ArtifactError$NotFound: not found: https://repo1.maven.org/maven2/maven-plugins/maven-cobertura-plugin/1.3/maven-cobertura-plugin-1.3.plugin
[error] 	at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$download$12(FileCache.scala:244)
[error] 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error] 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error] 	at scala.util.Success.map(Try.scala:213)
[error] 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error] 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (equellaserver / update) lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] https://repo1.maven.org/maven2/maven-plugins/maven-cobertura-plugin/1.3/maven-cobertura-plugin-1.3.plugin: not found: https://repo1.maven.org/maven2/maven-plugins/maven-cobertura-plugin/1.3/maven-cobertura-plugin-1.3.plugin
[error] https://repo1.maven.org/maven2/maven-plugins/maven-findbugs-plugin/1.3.1/maven-findbugs-plugin-1.3.1.plugin: not found: https://repo1.maven.org/maven2/maven-plugins/maven-findbugs-plugin/1.3.1/maven-findbugs-plugin-1.3.1.plugin
```

**Platform:**

- OS: Debian Linux

**Comment by edalex-ian** [comment]
BTW, one of the simple niceties I allude to is the simple additional detail of loading all the build.sbt files. Rather then the kind of useless:

```
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Resolving key references (20681 settings) ...
```

You get:

```
[info] Loading settings for project equella from build.sbt ...
[info] Loading settings for project Installer from build.sbt ...
[info] Loading settings for project UpgradeManager from build.sbt ...
[info] Loading settings for project UpgradeInstallation from build.sbt ...
[info] Loading settings for project conversion from build.sbt ...
[info] Loading settings for project adminTool from build.sbt ...
[info] Loading settings for project equellaserver from build.sbt ...
[info] Loading settings for project autotest from build.sbt ...
[info] Loading settings for project learningedge_config from build.sbt ...
[info] Loading settings for project com_tle_web_adminconsole from build.sbt ...
[info] Loading settings for project com_equella_reporting from build.sbt ...
[info] Loading settings for project com_equella_z3950 from build.sbt ...
[info] Loading settings for project com_equella_oai from build.sbt ...
[info] Loading settings for project com_tle_web_filemanager_applet from build.sbt ...
[info] Loading settings for project com_equella_srw from build.sbt ...
[info] Loading settings for project com_equella_core from build.sbt ...
[info] Loading settings for project org_eclipse_birt_osgi from build.sbt ...
[info] Loading settings for project com_tle_common_applet from build.sbt ...
[info] Loading settings for project org_hibernate from build.sbt ...
[info] Loading settings for project com_tle_platform_equella from build.sbt ...
[info] Loading settings for project OldTests from build.sbt ...
[info] Loading settings for project Tests from build.sbt ...
[info] Loading settings for project IntegTester from build.sbt ...
[info] Loading settings for project adminConsoleJar from build.sbt ...
[info] Loading settings for project filemanagerApplet from build.sbt ...
[info] Loading settings for project inplaceEditorJar from build.sbt ...
[info] Resolving key references (21048 settings) ...
```

**Comment by edalex-ian** [comment]
Unfortunately updating the sbt dependency in #1825 did not improve things. But this time I have included logs to capture the failure state for the latest 1.2.x and 1.3.x.

* [sbt-1.2.8.log](https://github.com/openequella/openEQUELLA/files/4777525/sbt-1.2.8.log)
* [sbt-1.3.4.log](https://github.com/openequella/openEQUELLA/files/4777526/sbt-1.3.4.log)

**Comment by edalex-ian** [comment]
To address the issues around `maven-cobertura-plugin` and `maven-findbugs-plugin`, we just need to upgrade Apache axiom in `Source/Server/equellaserver/build.sbt`. But alas, then we have a ton of deduplicate errors again.

**Comment by edalex-ian** [comment]
Ah! And upgrading Axiom runs us into an issue with the Blackboard code now using classes which are now private. See #1067 and the comments in there. (In the end it was decided to let it go stale, but now that's a blocker to upgrading SBT.)

(See also #1537.)

**Comment by edalex-ian** [comment]
Ah, looks like there's a sweet spot for Axiom upgrade:

```diff
-  "org.apache.ws.commons.axiom" % "axiom-api"              % "1.2.13",
-  "org.apache.ws.commons.axiom" % "axiom-impl"             % "1.2.13",
+  "org.apache.ws.commons.axiom" % "axiom-api"              % "1.2.15",
+  "org.apache.ws.commons.axiom" % "axiom-impl"             % "1.2.15",
```

Still has deduplicate issues, but at least possibly no code changes as well.

(Note, that's with SBT 1.4.9.)

**Comment by edalex-ian** [comment]
This is all done, we're now on 1.5.2.
