### ISSUE TITLE
Blackboard DB error when removing an Equella Object

### ISSUE THREAD

**Issue by smclaughlin520** [openequella/openEQUELLA#194]
The following happens in the Bb logs when removing an Equella Object from Bb. Happens with at least 6.3-QA2, the latest building block of 6.3, and the latest building block of 6.4.
 
 Not sure if there's any side effects to this issue. On the surface, doesn't look to affect the user (the Equella object is removed from the course and if the object was added to the gradebook, it is removed).
 
 {code}
 2015-07-15 15:55:58 -0400 - Error removing content - blackboard.persist.PersistenceException: A database error occurred.
 at blackboard.persist.impl.AbstractBaseDbPersister.runQuery(AbstractBaseDbPersister.java:197)
 at blackboard.persist.impl.AbstractBaseDbPersister.runQuery(AbstractBaseDbPersister.java:139)
 at blackboard.persist.content.impl.ContentDbPersisterImpl.deleteById(ContentDbPersisterImpl.java:251)
 at blackboard.persist.content.impl.ContentDbPersisterImpl.deleteById(ContentDbPersisterImpl.java:215)
 at blackboard.platform.coursecontent.impl.CourseContentManagerImpl.removeContent(CourseContentManagerImpl.java:153)
 at sun.reflect.GeneratedMethodAccessor3294.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:606)
 at blackboard.db.TransactionInterfaceFactory$TransactionHandler.invoke(TransactionInterfaceFactory.java:53)
 at com.sun.proxy.$Proxy736.removeContent(Unknown Source)
 at blackboard.webapps.blackboard.content.ContentRemovalHelper.remove(ContentRemovalHelper.java:86)
 at blackboard.webapps.blackboard.content.ContentRemovalHelper.removeContent(ContentRemovalHelper.java:76)
 at blackboard.webapps.blackboard.content.ContentRemovalHelper.removeContentItems(ContentRemovalHelper.java:64)
 at blackboard.webapps.blackboard.content.struts.RemoveItemAction.remove(RemoveItemAction.java:100)
 at sun.reflect.GeneratedMethodAccessor4481.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:606)
 at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:266)
 at blackboard.struts.SecureDispatchAction.dispatchMethod(SecureDispatchAction.java:49)
 at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:167)
 at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:413)
 at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:225)
 at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1858)
 at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:459)
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
 at blackboard.struts.BbActionServlet.service(BbActionServlet.java:103)
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
 at sun.reflect.GeneratedMethodAccessor618.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:606)
 at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:277)
 at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:274)
 at java.security.AccessController.doPrivileged(Native Method)
 at javax.security.auth.Subject.doAsPrivileged(Subject.java:536)
 at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:309)
 at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:169)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:297)
 at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:55)
 at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:191)
 at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:187)
 at java.security.AccessController.doPrivileged(Native Method)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:186)
 at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
 at sun.reflect.GeneratedMethodAccessor617.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:606)
 at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:277)
 at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:274)
 at java.security.AccessController.doPrivileged(Native Method)
 at javax.security.auth.Subject.doAsPrivileged(Subject.java:536)
 at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:309)
 at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:249)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:237)
 at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:55)
 at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:191)
 at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:187)
 at java.security.AccessController.doPrivileged(Native Method)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:186)
 at blackboard.platform.servlet.DevNonceFilter.doFilter(DevNonceFilter.java:68)
 at sun.reflect.GeneratedMethodAccessor616.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:606)
 at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:277)
 at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:274)
 at java.security.AccessController.doPrivileged(Native Method)
 at javax.security.auth.Subject.doAsPrivileged(Subject.java:536)
 at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:309)
 at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:249)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:237)
 at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:55)
 at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:191)
 at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:187)
 at java.security.AccessController.doPrivileged(Native Method)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:186)
 at blackboard.platform.servlet.B2ContextFilter.doFilter(B2ContextFilter.java:137)
 at sun.reflect.GeneratedMethodAccessor615.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:606)
 at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:277)
 at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:274)
 at java.security.AccessController.doPrivileged(Native Method)
 at javax.security.auth.Subject.doAsPrivileged(Subject.java:536)
 at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:309)
 at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:249)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:237)
 at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:55)
 at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:191)
 at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:187)
 at java.security.AccessController.doPrivileged(Native Method)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:186)
 at blackboard.platform.servlet.ContentTypeFilter.doFilter(ContentTypeFilter.java:53)
 at sun.reflect.GeneratedMethodAccessor613.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:606)
 at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:277)
 at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:274)
 at java.security.AccessController.doPrivileged(Native Method)
 at javax.security.auth.Subject.doAsPrivileged(Subject.java:536)
 at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:309)
 at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:249)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:237)
 at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:55)
 at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:191)
 at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:187)
 at java.security.AccessController.doPrivileged(Native Method)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:186)
 at blackboard.platform.servlet.XssServletFilter.doFilter(XssServletFilter.java:48)
 at sun.reflect.GeneratedMethodAccessor611.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:606)
 at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:277)
 at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:274)
 at java.security.AccessController.doPrivileged(Native Method)
 at javax.security.auth.Subject.doAsPrivileged(Subject.java:536)
 at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:309)
 at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:249)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:237)
 at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:55)
 at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:191)
 at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:187)
 at java.security.AccessController.doPrivileged(Native Method)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:186)
 at blackboard.platform.servlet.XssInputValidationFilter.doFilter(XssInputValidationFilter.java:40)
 at sun.reflect.GeneratedMethodAccessor609.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:606)
 at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:277)
 at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:274)
 at java.security.AccessController.doPrivileged(Native Method)
 at javax.security.auth.Subject.doAsPrivileged(Subject.java:536)
 at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:309)
 at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:249)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:237)
 at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:55)
 at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:191)
 at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:187)
 at java.security.AccessController.doPrivileged(Native Method)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:186)
 at blackboard.platform.servlet.ContentIsolationFilter.doFilter(ContentIsolationFilter.java:83)
 at sun.reflect.GeneratedMethodAccessor608.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:606)
 at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:277)
 at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:274)
 at java.security.AccessController.doPrivileged(Native Method)
 at javax.security.auth.Subject.doAsPrivileged(Subject.java:536)
 at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:309)
 at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:249)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:237)
 at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:55)
 at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:191)
 at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:187)
 at java.security.AccessController.doPrivileged(Native Method)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:186)
 at blackboard.platform.servlet.RequestSessionFilter.doFilter(RequestSessionFilter.java:155)
 at sun.reflect.GeneratedMethodAccessor607.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:606)
 at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:277)
 at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:274)
 at java.security.AccessController.doPrivileged(Native Method)
 at javax.security.auth.Subject.doAsPrivileged(Subject.java:536)
 at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:309)
 at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:249)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:237)
 at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:55)
 at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:191)
 at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:187)
 at java.security.AccessController.doPrivileged(Native Method)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:186)
 at blackboard.platform.servlet.RequestSecurityFilter.doFilter(RequestSecurityFilter.java:74)
 at sun.reflect.GeneratedMethodAccessor606.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:606)
 at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:277)
 at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:274)
 at java.security.AccessController.doPrivileged(Native Method)
 at javax.security.auth.Subject.doAsPrivileged(Subject.java:536)
 at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:309)
 at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:249)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:237)
 at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:55)
 at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:191)
 at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:187)
 at java.security.AccessController.doPrivileged(Native Method)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:186)
 at blackboard.platform.servlet.RequestClassParamFilter.doFilter(RequestClassParamFilter.java:47)
 at sun.reflect.GeneratedMethodAccessor605.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:606)
 at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:277)
 at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:274)
 at java.security.AccessController.doPrivileged(Native Method)
 at javax.security.auth.Subject.doAsPrivileged(Subject.java:536)
 at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:309)
 at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:249)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:237)
 at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:55)
 at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:191)
 at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:187)
 at java.security.AccessController.doPrivileged(Native Method)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:186)
 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
 at blackboard.webapps.blackboard.plugin.web.PluginsRequestRedirectValve.invoke(PluginsRequestRedirectValve.java:62)
 at blackboard.webapps.blackboard.blog.web.BlogRequestRedirectValve.invoke(BlogRequestRedirectValve.java:63)
 at blackboard.plugin.assignment.util.RequestRedirectValve.invoke(RequestRedirectValve.java:65)
 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
 at org.apache.catalina.valves.StuckThreadDetectionValve.invoke(StuckThreadDetectionValve.java:221)
 at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
 at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:683)
 at blackboard.tomcat.valves.LoggingRemoteIpValve.invoke(LoggingRemoteIpValve.java:44)
 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
 at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
 at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
 at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1736)
 at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1695)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
 at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
 at java.lang.Thread.run(Thread.java:744)
 Caused by: java.sql.SQLException: ORA-01403: no data found
 ORA-06512: at ""BBLEARN.COURSE_CONTENTS_RM"", line 21
 ORA-06512: at line 1
 
 at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
 at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
 at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1059)
 at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:522)
 at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257)
 at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:587)
 at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:220)
 at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:48)
 at oracle.jdbc.driver.T4CCallableStatement.executeForRows(T4CCallableStatement.java:938)
 at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1150)
 at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:4798)
 at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:4901)
 at oracle.jdbc.driver.OracleCallableStatement.execute(OracleCallableStatement.java:5631)
 at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1385)
 at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172)
 at blackboard.db.impl.MonitoringConnectionPool$SQLRecorder.execute(MonitoringConnectionPool.java:218)
 at blackboard.db.impl.MonitoringConnectionPool$MonitoringCallableStatement.execute(MonitoringConnectionPool.java:634)
 at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172)
 at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172)
 at blackboard.db.impl.SafetyNetCallableStatement.execute(SafetyNetCallableStatement.java:58)
 at blackboard.persist.impl.StoredProcedureQuery.doExecute(StoredProcedureQuery.java:304)
 at blackboard.persist.impl.Query.executeQuery(Query.java:148)
 at blackboard.persist.impl.Query.executeQuery(Query.java:114)
 at blackboard.persist.impl.AbstractBaseDbPersister$DbConnectivityPrivilege.run(AbstractBaseDbPersister.java:276)
 at java.security.AccessController.doPrivileged(Native Method)
 at blackboard.persist.impl.AbstractBaseDbPersister.runQuery(AbstractBaseDbPersister.java:168)
 ... 222 more
 {code}"

Issue Converted from original Equella JIRA

**Comment by smclaughlin520** [comment]
Additional Comments from Original JIRA

XXXXX was able to provide the details for the COUSE_CONTENTS_RM stored procedure. Not sure what to make of it. Might have to delve into debugging the Blackboard to proceed.
 
 {code:sql}
 PROCEDURE course_contents_rm(
  p1 IN NUMBER := NULL,
  crsmain_pk1 IN NUMBER := NULL,
  is_course_delete IN NUMBER := 0
 )
 IS
  v_crsmain_pk1 NUMBER;
  c_position_0 NUMBER;
  c_parent_pk1 NUMBER;
  c_position_f NUMBER;
  commit_flag NUMBER;
  CURSOR cur_crscntnts IS
  SELECT descendant_pk1
  FROM x_course_contents
  WHERE ancestor_pk1 = p1
  ORDER BY distance DESC;
 BEGIN
  v_crsmain_pk1 := crsmain_pk1;
  commit_flag := is_commit_disabled();
 
  IF ( p1 IS NOT NULL ) THEN
  c_position_f := 0;
  SELECT count(*) INTO c_position_f FROM course_contents WHERE PK1 = p1;
 
  IF ( c_position_f > 0 ) THEN
  SELECT PARENT_PK1 INTO c_parent_pk1 FROM course_contents WHERE PK1 = p1;
  END IF;
 
  FOR currow IN cur_crscntnts LOOP
  rm_course_contents( currow.descendant_pk1 );
  END LOOP;
 
  rm_course_contents( p1, is_course_delete );
 
  DELETE FROM x_course_contents WHERE descendant_pk1 IN (
  SELECT descendant_pk1 FROM x_course_contents WHERE ancestor_pk1 = p1);
 
  DELETE FROM x_course_contents WHERE descendant_pk1 = p1;
 
  IF ( c_parent_pk1 IS NOT NULL ) THEN
  c_position_0 := 0;
  c_position_f := 0;
 
  SELECT count(*) INTO c_position_f FROM course_contents WHERE PARENT_PK1 = c_parent_pk1;
 
  IF ( c_position_f > 0 ) THEN
 FOR cur IN (
  SELECT pk1 FROM course_contents
  WHERE PARENT_PK1 = c_parent_pk1
  ORDER BY position, pk1 )
 LOOP
  UPDATE course_contents SET position = c_position_0 WHERE pk1 = cur.pk1;
  c_position_0 := c_position_0 + 1;
  IF ( commit_flag = 0 ) THEN
  COMMIT;
  END IF;
 END LOOP;
  END IF;
  END IF;
 
  ELSIF ( crsmain_pk1 IS NOT NULL ) THEN
 
  DELETE FROM files WHERE EXISTS (
  SELECT 1 FROM group_attempt_files g
  WHERE g.files_pk1 = files.pk1 AND g.group_attempt_pk1 IN (
 SELECT gat.pk1 FROM group_attempt gat
 JOIN course_content_group ga ON gat.course_content_group_pk1 = ga.pk1
 JOIN course_contents cc ON cc.pk1 = ga.course_contents_pk1
 WHERE cc.crsmain_pk1 = v_crsmain_pk1)
  );
 
  FOR myid IN (
  SELECT pk1 FROM course_contents
  WHERE crsmain_pk1 = v_crsmain_pk1
  ORDER BY parent_pk1 DESC NULLS LAST, pk1 DESC)
  LOOP
  course_contents_rm( p1 => myid.pk1, is_course_delete => 1 );
  END LOOP;
 
  END IF;
 
 END;
 {code}"
