### ISSUE TITLE
In place file editor no longer works

### ISSUE THREAD

**Issue by cbeach47** [openequella/openEQUELLA#2501]
**Describe the bug**
Launching the in place file editor brings up the java console, but no widgets / content is loaded.  More often then not, the error below is thrown in the logs, and I've captured the following when trying to save / exit the dialog:

```
msg: TypeError: applet.isSynchronising is not a function url:http://192.168.1.124:9000/oeq/local/p/r/2020.2.0/com.equella.core/jquerycore/jquery.js line 339 > eval line:125
```

Since applets are legacy tech, and only seem to work on old browsers such as IE 11 and FF 47 or lower, the answer to this issue may well be alignment that this feature is now retired and the links in the edit attachment dialog should be removed.

**To Reproduce**

1. Go to a simple text file attachment
2. Click `edit`
3. Click `edit file with default editor`

**Expected behavior**
The OS text editor should launch with the contents of the text file

**Stacktrace**

```
java.lang.IllegalArgumentException: unknown plug-in ID - com.tle.web.inplaceeditor
at org.java.plugin.registry.xml.PluginRegistryImpl.getPluginDescriptor(PluginRegistryImpl.java:753)
at com.tle.core.plugins.AbstractPluginService.getClassLoader(AbstractPluginService.java:180)
at com.tle.web.resources.AbstractResourcesServlet.service(AbstractResourcesServlet.java:59)
at com.tle.web.resources.ResourcesServlet.service(ResourcesServlet.java:91)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
at com.tle.web.dispatcher.ServletDispatcher.dispatch(ServletDispatcher.java:95)
at com.tle.web.dispatcher.RequestDispatchFilter.doFilter(RequestDispatchFilter.java:91)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:748)
```

**Platform:**

- openEQUELLA Version: 2020.1.4.OSE, tip of develop on 2020-11-05
- OS: browser on Windows 10, oEQ on ubuntu
- Browser Firefox 47, IE 11

**Additional context**
The file manager on the same browser / oEQ versions work.

**Comment by cbeach47** [comment]
Another error showed up related to the IPFE in 2020.1.6 - When trying to launch the applet, it fails with the following errors in the logs.  
```
java.lang.IllegalArgumentException: unknown plug-in ID - com.tle.web.inplaceeditor
	at org.java.plugin.registry.xml.PluginRegistryImpl.getPluginDescriptor(PluginRegistryImpl.java:753)
	at com.tle.core.plugins.AbstractPluginService.getClassLoader(AbstractPluginService.java:180)
	at com.tle.web.resources.AbstractResourcesServlet.service(AbstractResourcesServlet.java:59)
	at com.tle.web.resources.ResourcesServlet.service(ResourcesServlet.java:91)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at com.tle.web.dispatcher.ServletDispatcher.dispatch(ServletDispatcher.java:95)
	at com.tle.web.dispatcher.RequestDispatchFilter.doFilter(RequestDispatchFilter.java:91)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:609)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1623)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

```
