### ISSUE TITLE
500 error happens when save and continue an Item of Collection 'Books' 

### ISSUE THREAD

**Issue by PenghaiZhang** [openequella/openEQUELLA#2607]
**Describe the bug**
On unstable/stable, when contribute an Item that is of Collection 'Books',  two sorts of 500 error can happen after the 'save and continue' button is clicked. This bug happens in both New and Old UI.

Update: This bug seems to happen only in the `Books` of `vanilla`. I tried to reproduce in institution `charlie` but no error was thrown.

Update again:  Locally, this error does not happen if I use a normal user such as AutoTest. If I use the administrator one,  the error appears.

**To Reproduce**

1. Go to Contribute page
2. Select 'Books'
3. In the Wizard, put some texts in certain fields or do just nothing, and then click 'save and continue'

**Expected behavior**
It should show the snack bar indicating 'save and continue' is done.

**Screenshots**
![image](https://user-images.githubusercontent.com/47203811/102161802-17536280-3edc-11eb-9914-9ec6859e93c7.png)

![image](https://user-images.githubusercontent.com/47203811/102161836-29cd9c00-3edc-11eb-93fd-a2a45e157e96.png)

**Stacktrace**
15:34:09,464 ERROR [RestEasyExceptionMapper] REST API error
com.tle.common.scripting.ScriptException: org.mozilla.javascript.WrappedException: Wrapped java.lang.IllegalArgumentException: Element value must not be null (saveOperation#105)
	at com.tle.core.scripting.service.ScriptingServiceImpl$1.run(ScriptingServiceImpl.java:210)
	at org.mozilla.javascript.Context.call(Context.java:554)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
	at com.tle.core.scripting.service.ScriptingServiceImpl.executeInternal(ScriptingServiceImpl.java:159)
	at com.tle.core.scripting.service.ScriptingServiceImpl.executeScript(ScriptingServiceImpl.java:132)
	at com.tle.core.item.service.impl.ItemServiceImpl.executeScript(ItemServiceImpl.java:1071)
	at com.tle.core.item.standard.operations.SaveOperation.runSaveScript(SaveOperation.java:173)
	at com.tle.core.item.standard.operations.SaveOperation.execute(SaveOperation.java:115)
	at com.tle.core.item.service.impl.ItemServiceImpl.execute(ItemServiceImpl.java:858)
	at com.tle.core.item.service.impl.ItemServiceImpl.execute(ItemServiceImpl.java:817)
	at com.tle.core.item.service.impl.ItemServiceImpl.runOperation(ItemServiceImpl.java:722)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at com.tle.core.item.service.impl.ItemServiceImpl.operation(ItemServiceImpl.java:939)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at com.tle.web.wizard.impl.WizardServiceImpl.doSave(WizardServiceImpl.java:224)
	at com.tle.web.wizard.command.SaveAndContinue.execute(SaveAndContinue.java:60)
	at com.tle.web.wizard.section.WizardBodySection.command(WizardBodySection.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.tle.web.sections.events.js.MethodInvocationEventGenerator$1.fireDirect(MethodInvocationEventGenerator.java:94)
	at com.tle.web.sections.events.AbstractDirectEvent.fire(AbstractDirectEvent.java:86)
	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:420)
	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:394)
	at com.tle.web.sections.generic.DefaultSectionInfo.processQueue(DefaultSectionInfo.java:388)
	at com.tle.web.sections.registry.AbstractSectionsController.execute(AbstractSectionsController.java:44)
	at com.tle.web.api.LegacyContentApi.$anonfun$submit$1(LegacyContentApi.scala:455)
	at com.tle.web.api.LegacyContentApi.withTreePath(LegacyContentApi.scala:323)
	at com.tle.web.api.LegacyContentApi.submit(LegacyContentApi.scala:452)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:138)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:543)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:432)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:393)
	at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:395)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:337)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:440)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135)
	at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:138)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:215)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:245)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:61)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at com.tle.web.remoting.resteasy.RestEasyServlet.service(RestEasyServlet.java:140)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at com.tle.web.dispatcher.ServletDispatcher.dispatch(ServletDispatcher.java:95)
	at com.tle.web.dispatcher.RequestDispatchFilter.doFilter(RequestDispatchFilter.java:91)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:880)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1601)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.mozilla.javascript.WrappedException: Wrapped java.lang.IllegalArgumentException: Element value must not be null (saveOperation#105)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1899)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:160)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
	at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:121)
	at org.mozilla.javascript.Context.evaluateString(Context.java:1234)
	at com.tle.core.scripting.service.ScriptingServiceImpl$1.run(ScriptingServiceImpl.java:198)
	... 78 more
Caused by: java.lang.IllegalArgumentException: Element value must not be null
	at com.dytech.devlib.PropBagEx.setNode(PropBagEx.java:1066)
	at com.dytech.edge.common.PropBagWrapper$PathOverride.setNode(PropBagWrapper.java:339)
	at com.dytech.edge.common.PropBagWrapper.set(PropBagWrapper.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
	... 87 more
**Platform:**

- OpenEquella Version: 2020.1 2020.2
- OS: Ubuntu 18.04
- Browser: Chrome

**Additional context**
Not applicable.

**Comment by mrblippy** [comment]
It's caused by some dodgy save scripting in the vanilla institution https://github.com/openequella/openequella.github.io/issues/42

**Comment by cathfitz** [comment]
Internal collection - another ticket exists to look at this
