### ISSUE TITLE
Null pointer when adding a cal portion to and lms that is already active in another course

### ISSUE THREAD

**Issue by mrblippy** [openequella/openEQUELLA#278]
Found in blackboard, but i would think it would happen in any lms. Steps to replicate:

- Contribute a cal portion to equella, and activate it
- Startup a selection session in blackboard, find your cal item and try to add the attachment (click the blue plus button)
- It should null pointer, with the following errors in the logs

`14:43:52,781 ERROR [DefaultErrorSection] Error at http://charliedesk:8080/vanilla2/items/76e980b2-d775-42be-8666-f155d8964143/1/ :
java.lang.NullPointerException
	at com.tle.web.viewitem.section.RootItemFileSection.renderHtml(RootItemFileSection.java:259)
	at com.tle.web.sections.render.HtmlRendererListener.render(HtmlRendererListener.java:50)
	at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:82)
	at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:24)
	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:577)
	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:472)
	at com.tle.web.sections.generic.WrappedSectionInfo.processEvent(WrappedSectionInfo.java:245)
	at com.tle.web.sections.events.StandardRenderEventContext.processEvent(StandardRenderEventContext.java:311)
	at com.tle.web.sections.equella.AbstractRootModalSessionSection.renderHtml(AbstractRootModalSessionSection.java:71)
	at com.tle.web.sections.render.HtmlRendererListener.render(HtmlRendererListener.java:50)
	at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:82)
	at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:24)
	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:577)
	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:472)
	at com.tle.web.sections.generic.WrappedSectionInfo.processEvent(WrappedSectionInfo.java:245)
	at com.tle.web.sections.events.StandardRenderEventContext.processEvent(StandardRenderEventContext.java:311)
	at com.tle.web.sections.generic.AbstractSection.renderToTemplate(AbstractSection.java:112)
	at com.tle.web.integration.IntegrationSection.renderHtml(IntegrationSection.java:135)
	at com.tle.web.sections.render.HtmlRendererListener.render(HtmlRendererListener.java:50)
	at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:82)
	at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:24)
	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:577)
	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:472)
	at com.tle.web.sections.generic.WrappedSectionInfo.processEvent(WrappedSectionInfo.java:245)
	at com.tle.web.sections.events.StandardRenderEventContext.processEvent(StandardRenderEventContext.java:311)
	at com.tle.web.template.RenderTemplate.renderHtml(RenderTemplate.java:155)
	at com.tle.web.sections.render.HtmlRendererListener.render(HtmlRendererListener.java:50)
	at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:82)
	at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:24)
	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:577)
	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:472)
	at com.tle.web.sections.registry.SectionsControllerImpl.renderForward(SectionsControllerImpl.java:103)
	at com.tle.web.sections.registry.SectionsControllerImpl.execute(SectionsControllerImpl.java:79)
	at com.tle.web.viewable.servlet.ItemServlet.service(ItemServlet.java:124)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at com.tle.web.dispatcher.ServletDispatcher.dispatch(ServletDispatcher.java:98)
	at com.tle.web.dispatcher.RequestDispatchFilter.doFilter(RequestDispatchFilter.java:102)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1085)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1556)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1513)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
14:43:52,785 ERROR [DefaultErrorSection] Error at http://charliedesk:8080/vanilla2/items/76e980b2-d775-42be-8666-f155d8964143/1/ :
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at com.tle.web.copyright.section.AbstractCopyrightSummarySection.addAlreadyActivated(AbstractCopyrightSummarySection.java:435)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.tle.web.sections.events.js.MethodInvocationEventGenerator$1.fireDirect(MethodInvocationEventGenerator.java:100)
	at com.tle.web.sections.events.AbstractDirectEvent.fire(AbstractDirectEvent.java:95)
	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:503)
	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:472)
	at com.tle.web.sections.generic.DefaultSectionInfo.processQueue(DefaultSectionInfo.java:465)
	at com.tle.web.sections.registry.SectionsControllerImpl.execute(SectionsControllerImpl.java:78)
	at com.tle.web.viewable.servlet.ItemServlet.service(ItemServlet.java:124)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at com.tle.web.dispatcher.ServletDispatcher.dispatch(ServletDispatcher.java:98)
	at com.tle.web.dispatcher.RequestDispatchFilter.doFilter(RequestDispatchFilter.java:102)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1085)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1556)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1513)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by doolse** [comment]
@abidingotter Shouldn't you not be allow to add something that has been activated in another course?

**Comment by abidingotter** [comment]
You would think so, but I'm pretty sure if it's activated at all then you can select the attachment.  I would need to find the original user story.

**Comment by mrblippy** [comment]
Found the test case that says this should work. It's eqos-1672
