### ISSUE TITLE
Pre login notice Images don't work

### ISSUE THREAD

**Issue by SammyIsConfused** [openequella/openEQUELLA#2833]
**Describe the bug**
So when you upload an image to the pre login notice editor, it comes up blank. In the resource editor logs we get errors during getting the MIME type of this image.

**To Reproduce**

1. Go to `General-> Login notice editor` in the settings
2. In the TinyMCE panel, upload an Image (not an image as an URL, a direct upload)
3. Note that the image comes up blank in the editor.
4. Note that there are errors in the resource centre logs.

**Expected behavior**
Images should be able to be placed within a login notice. 

**Screenshots**
![image](https://user-images.githubusercontent.com/24543345/111932352-557ea480-8b11-11eb-950a-fa6d1a217ed1.png)

**Stacktrace**
If applicable, a stacktrace to help explain your problem.
```
13:17:28,098 ERROR [RestEasyExceptionMapper] REST API error
java.nio.file.NoSuchFileException: EquellaProjectFolder/fork/openEQUELLA/Dev/learningedge-config/data/filestore/Institutions/vanilla/Custom2/Image from iOS.jpg
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at org.apache.sis.internal.storage.io.ChannelFactory$2.readable(ChannelFactory.java:255)
	at org.apache.sis.storage.StorageConnector.createChannelDataInput(StorageConnector.java:939)
	at org.apache.sis.storage.StorageConnector.lambda$static$0(StorageConnector.java:182)
	at org.apache.sis.storage.StorageConnector.getStorageAs(StorageConnector.java:843)
	at org.apache.sis.storage.StorageConnector.createByteBuffer(StorageConnector.java:1027)
	at org.apache.sis.storage.StorageConnector.getStorageAs(StorageConnector.java:843)
	at org.apache.sis.storage.netcdf.NetcdfStoreProvider.probeContent(NetcdfStoreProvider.java:175)
	at org.apache.sis.storage.DataStoreRegistry.lookup(DataStoreRegistry.java:189)
	at org.apache.sis.storage.DataStoreRegistry.probeContentType(DataStoreRegistry.java:113)
	at org.apache.sis.storage.DataStores.probeContentType(DataStores.java:102)
	at org.apache.sis.internal.storage.StoreTypeDetector.probeContentType(StoreTypeDetector.java:55)
	at java.nio.file.Files.probeContentType(Files.java:1618)
	at com.tle.core.services.impl.FileSystemServiceImpl.getMimeType(FileSystemServiceImpl.java:354)
	at com.tle.core.settings.loginnotice.impl.LoginNoticeServiceImpl.getMimeType(LoginNoticeServiceImpl.java:172)
	at com.tle.web.api.loginnotice.impl.PreLoginNoticeResourceImpl.getPreLoginNoticeImage(PreLoginNoticeResourceImpl.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:138)
```
	
**Platform:**

- OpenEquella Version: 2020.2 onwards
- OS: Agnostic
- Browser: Agnostic

**Comment by cathfitz** [comment]
Fixed and tested
