### ISSUE TITLE
Deletion of hierarchies only apparent in UI after logging out and back in

### ISSUE THREAD

**Issue by SammyIsConfused** [openequella/openEQUELLA#3104]
**Describe the bug**
When you delete a hierarchy via the admin console, the item in the navigation menu for this hierarchy isn’t removed until you logout. Clicking on it will cause a 500 error. This happens in the old and the new UI.

**To Reproduce**

1. Log into an institution with hierarchy set up.
2. Connect to the institution via the admin console.
3. Delete one or more hierarchies from the Hierarchy Editor.
4. Refresh the logged in openEQUELLA page from step 1.
5. Note that the delete hierarchy is still there as a menu item.
6. Note that clicking the menu item throws a 500 error. 
7. Log out and log back in.
8. Note that the menu item has disappeared as it should.

**Expected behavior**
Being something that is changed irregularly it should be fine to show the situation as seen in the Old UI. This is not an uncommon situation across various software platforms. 
However, there are differences between the errors that are shown in the old and new UIs. The old UI shows the error in a respectable way, clearly outlining the reason for the problem. 
The new UI displays as a full page 500 Internal Server Error, making the problem appear much more serious than it actually is. So - the expected behaviour would be to handle the situation in a user friendly way in the new UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/24543345/121988420-9a973780-cddd-11eb-82e8-98135c36200d.png)
![image](https://user-images.githubusercontent.com/24543345/121988441-a551cc80-cddd-11eb-8ac8-1a76f71588f4.png)

**Stacktrace**
```
3:28:04,429 ERROR [DefaultErrorSection] Error at http://localhost:8080/rest/hierarchy.do?topic=91a08805-d5f9-478d-aaaf-eff61a266667 :
java.lang.IllegalArgumentException: Could not find topic 91a08805-d5f9-478d-aaaf-eff61a266667
	at com.tle.web.hierarchy.section.TopicDisplaySection$ExtendedTopicDisplayModel.ensureParsed(TopicDisplaySection.java:338)
	at com.tle.web.hierarchy.section.TopicDisplaySection$ExtendedTopicDisplayModel.getTopic(TopicDisplaySection.java:311)
	at com.tle.web.hierarchy.section.TopicDisplaySection.renderHtml(TopicDisplaySection.java:162)
	at com.tle.web.sections.render.HtmlRendererListener.render(HtmlRendererListener.java:46)
	at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:74)
	at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:26)
	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:471)
	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:394)
	at com.tle.web.sections.generic.WrappedSectionInfo.processEvent(WrappedSectionInfo.java:210)
	at com.tle.web.sections.events.StandardRenderEventContext.processEvent(StandardRenderEventContext.java:270)
	at com.tle.web.sections.SectionUtils.renderSectionResult(SectionUtils.java:650)
	at com.tle.web.search.base.AbstractRootSearchSection.getTemplateResult(AbstractRootSearchSection.java:122)
	at com.tle.web.sections.equella.layout.TwoColumnLayout.setupTemplate(TwoColumnLayout.java:42)
	at com.tle.web.sections.equella.layout.OneColumnLayout.renderHtml(OneColumnLayout.java:70)
	at com.tle.web.search.base.ContextableSearchSection.renderHtml(ContextableSearchSection.java:76)
	at com.tle.web.hierarchy.section.RootHierarchySection.renderHtml(RootHierarchySection.java:81)
	at com.tle.web.sections.render.HtmlRendererListener.render(HtmlRendererListener.java:46)
	at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:74)
	at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:26)
	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:471)
	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:394)
	at com.tle.web.sections.generic.WrappedSectionInfo.processEvent(WrappedSectionInfo.java:210)
	at com.tle.web.sections.events.StandardRenderEventContext.processEvent(StandardRenderEventContext.java:270)
	at com.tle.web.template.RenderTemplate.renderHtml(RenderTemplate.java:169)
	at com.tle.web.sections.render.HtmlRendererListener.render(HtmlRendererListener.java:46)
	at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:74)
	at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:26)
	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:471)
	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:394)
	at com.tle.web.sections.registry.AbstractSectionsController.renderFromRoot(AbstractSectionsController.java:69)
	at com.tle.web.sections.registry.AbstractSectionsController.renderForward(AbstractSectionsController.java:59)
	at com.tle.web.sections.registry.AbstractSectionsController.execute(AbstractSectionsController.java:45)
	at com.tle.web.sections.registry.SectionsServlet.service(SectionsServlet.java:71)
	at com.tle.web.sections.equella.MultipartSectionsServlet.service(MultipartSectionsServlet.java:48)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at com.tle.web.dispatcher.ServletDispatcher.dispatch(ServletDispatcher.java:95)
	at com.tle.web.dispatcher.RequestDispatchFilter.doFilter(RequestDispatchFilter.java:91)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:764)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Platform:**

- OpenEquella Version: 2021.1+
- OS: Agnostic
- Browser: Agnostic

**Comment by edalex-ian** [comment]
Being something that is changed irregularly it should be fine to show the situation as seen in the Old UI. This is not an uncommon situation across much software.

I would suggest the real issue here is the rather critical issue being seen in the New UI. Maybe the 'Expected behaviour' is that the situation is handled in a user friendly manner in the New UI.

**Comment by SammyIsConfused** [comment]
> Being something that is changed irregularly it should be fine to show the situation as seen in the Old UI. This is not an uncommon situation across much software.
> 
> I would suggest the real issue here is the rather critical issue being seen in the New UI. Maybe the 'Expected behaviour' is that the situation is handled in a user friendly manner in the New UI.

@edalex-ian Updated the issue to account for that - thanks Ian :+1:

**Comment by cathfitz** [comment]
Will be looked at in new UI error handling
