### ISSUE TITLE
Items with EQUELLA resource attachments that have been set to latest live version breaks the new Search U/I.

### ISSUE THREAD

**Issue by cathfitz** [openequella/openEQUELLA#3558]
Tested in 2021.1.1, found by a client, but could affect other institutions.

**Overview:**

If you have an institution with multiple collections, one of which has an attachment control to allow the selection of a second collection's resources as an attachment.  If you have your integration settings that allow the user to select the latest live version (0) and attach that, then when you perform a search, you'll get a "Request failed with code 500" message and no search results.

**Example:**

- I've contributed one resource into the "Remote Items Collection".
- I've contributed two resources into the "Collection with Remote Items".
- Both link to the single item in the "Remote Items Collection":

Item with just a local attachment and a EQUELLA Resource Attachment fixed at version 2 

Item with just a local attachment and a EQUELLA Resource Attachment fixed at version 0 (latest live version). Archive this item and the error goes away. 

1. Login as sysadmin/equella
2. Perform a regular (basic) search (no collections selected).  You'll see the error.
3. Refine the search to just the "Remote Items Collection" and you'll see one resource.
4. Refine the search to just the "Collection with Remote Items" and you'll see the error.

Go to Manage Resources and archive the item:

Item with just a local attachment and a EQUELLA Resource Attachment fixed at version 0 (latest live version). 

Then go back and perform a basic search.  You'll see two resources.  Refining by each collection also returns results.

The stack trace says:

```
2021-11-03 12:03:31,140 context="00360c14-6509-4fd0-8f85-dde60684999d" level="ERROR" category="RestEasyExceptionMapper" message="REST API error"
java.lang.Error: Real version numbers are used in ItemService
        at com.tle.core.item.service.impl.ItemServiceImpl.ensureItemKey(ItemServiceImpl.java:253)
        at com.tle.core.item.service.impl.ItemServiceImpl.getUnsecureIfExists(ItemServiceImpl.java:270)
        at com.tle.web.api.search.SearchHelper$.getBrokenAttachmentStatusForResourceAttachment(SearchHelper.scala:340)
        at com.tle.web.api.search.SearchHelper$.recurseBrokenAttachmentCheck(SearchHelper.scala:361)
        at com.tle.web.api.search.SearchHelper$.$anonfun$convertToAttachment$3(SearchHelper.scala:284)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at scala.collection.TraversableLike.map(TraversableLike.scala:286)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at com.tle.web.api.search.SearchHelper$.$anonfun$convertToAttachment$1(SearchHelper.scala:281)
        at scala.Option.map(Option.scala:230)
        at com.tle.web.api.search.SearchHelper$.convertToAttachment(SearchHelper.scala:277)
        at com.tle.web.api.search.SearchHelper$.convertToItem(SearchHelper.scala:256)
        at com.tle.web.api.search.SearchResource.$anonfun$searchItems$3(SearchResource.scala:70)
        at scala.collection.immutable.List.map(List.scala:293)
        at com.tle.web.api.search.SearchResource.searchItems(SearchResource.scala:70)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:138)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:543)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:432)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:393)
        at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:395)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:337)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:440)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135)
        at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:138)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:215)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:245)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:61)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
        at com.tle.web.remoting.resteasy.RestEasyServlet.service(RestEasyServlet.java:142)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at com.tle.web.dispatcher.ServletDispatcher.dispatch(ServletDispatcher.java:95)
        at com.tle.web.dispatcher.RequestDispatchFilter.doFilter(RequestDispatchFilter.java:91)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:764)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:887)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1684)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by snehanaik22** [comment]
Tested.
