### ISSUE TITLE
Error adding portions via Equella resource attachment control

### ISSUE THREAD

**Issue by mrblippy** [openequella/openEQUELLA#396]
Steps to reproduce:
* Contribute a holding item
* Contribute a portion item, and link it to the item from step 1
* Start a contribution that contains an EQUELLA Resources attachment control
* In the selection session, click the portion item you added in step 2
* Click the Blue plus button
![capture](https://user-images.githubusercontent.com/4625498/33197422-66ad98fa-d139-11e7-8901-99cf2c45f2b6.PNG)

You will get the following error 'No value present', with a corresponding stacktrace in the logs

06:03:53,852 ERROR [DefaultErrorSection] Error at https://betadev.equella.net/charlie/items/716ce56d-4908-4285-99a3-6dd36444b8d2/1/ :
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135)
        at com.tle.web.copyright.section.AbstractCopyrightSummarySection.addAlreadyActivated(AbstractCopyrightSummarySection.java:435)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.tle.web.sections.events.js.MethodInvocationEventGenerator$1.fireDirect(MethodInvocationEventGenerator.java:100)
        at com.tle.web.sections.events.AbstractDirectEvent.fire(AbstractDirectEvent.java:95)
        at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:503)
        at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:472)
        at com.tle.web.sections.generic.DefaultSectionInfo.processQueue(DefaultSectionInfo.java:465)
        at com.tle.web.sections.registry.SectionsControllerImpl.execute(SectionsControllerImpl.java:78)
        at com.tle.web.viewable.servlet.ItemServlet.service(ItemServlet.java:124)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
        at com.tle.web.dispatcher.ServletDispatcher.dispatch(ServletDispatcher.java:98)
        at com.tle.web.dispatcher.RequestDispatchFilter.doFilter(RequestDispatchFilter.java:102)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:673)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1085)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
        at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1556)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1513)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

**Comment by mrblippy** [comment]
I can add the portion attachment now, but clicking the unactivated attachment goes to https://betadev.equella.net/charlie/undefined

See https://betadev.equella.net/charlie/items/083fc6a5-aefe-43d2-8d9e-2c302323027d/1/ for an example
