### ISSUE TITLE
Silently fails to extract institution

### ISSUE THREAD

**Issue by goetzk** [openequella/openEQUELLA#592]
Hi,
While working my way through the docs (https://github.com/equella/equella.github.io) I came to the point of needing an institution (I'm using version 6.6-Stable.OSE)

I found one (in the documentation repository) mentioned in several equalla-users posts so tried to load that in to my equella instance through the "Import new institution" functionality.

https://groups.google.com/a/apereo.org/forum/#!searchin/equella-users/Import$20institution|sort:date/equella-users/Ybg_Kyu8Ar8/UnatUp5RAwAJ
https://groups.google.com/a/apereo.org/forum/#!searchin/equella-users/Import$20institution%7Csort:date/equella-users/2CLsoPu_pY4/8bhqL_hCAwAJ

I'm unable to extract that tgz file because, it turns out, I downloaded the redirect notice not the actual file itself. Problem is, equella didn't mention that. It logs an error then sits on the import page saying "Unzipping file... " and providing no indication the file is invalid.

```
<tr><td>15:34:36,756</td><td>2fd13ccd-f732-4ca7-a1ea-03e62caf7dc3</td><td><font color="#993300"><strong>ERROR</strong></font></td><td>ImportTab</td>
<td>Error unzipping institution file</td></tr>
<tr><td bgcolor="#993300" style="color:White; font-size : xx-small;" colspan="5">java.util.zip.ZipException: Not in GZIP format
<br>&nbsp;&nbsp;&nbsp;&nbsp;	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
<br>&nbsp;&nbsp;&nbsp;&nbsp;	at java.util.zip.GZIPInputStream.&lt;init&gt;(GZIPInputStream.java:79)
<br>&nbsp;&nbsp;&nbsp;&nbsp;	at java.util.zip.GZIPInputStream.&lt;init&gt;(GZIPInputStream.java:91)
<br>&nbsp;&nbsp;&nbsp;&nbsp;	at com.tle.core.util.archive.ArchiveType$3.createExtractor(ArchiveType.java:131)
<br>&nbsp;&nbsp;&nbsp;&nbsp;	at com.tle.core.services.impl.FileSystemServiceImpl.unzipPrivate(FileSystemServiceImpl.java:1001)
<br>&nbsp;&nbsp;&nbsp;&nbsp;	at com.tle.core.services.impl.FileSystemServiceImpl.unzipFile(FileSystemServiceImpl.java:882)
<br>&nbsp;&nbsp;&nbsp;&nbsp;	at com.tle.web.institution.tab.ImportTab$1.doRun(ImportTab.java:176)
<br>&nbsp;&nbsp;&nbsp;&nbsp;	at com.tle.common.usermanagement.user.AuthenticatedThread.run(AuthenticatedThread.java:70)
</td></tr>
```

I'm hoping the error can be surfaced for the information of future misguided uploaders.

**Comment by goetzk** [comment]
Further to this - I tried uploading valid tgz and zip files and both silently failed _in Safari_ 12. I uploaded a tgz from chrome and it worked instantly so its possible this isn't actually an issue.

**Comment by goetzk** [comment]
afaik this problem hasn't been solved yet so here is your ping.

**Comment by goetzk** [comment]
I'm unsure if this bug was fixed but I'm going to unsubscribe from notifications so i don't have to keep hearing from the bot.
