### ISSUE TITLE
Broken workflow language string

### ISSUE THREAD

**Issue by mrblippy** [openequella/openEQUELLA#808]
**Describe the bug**
I just saw this in a client's logs

Missing language string for 'com.tle.web.itemadmin.error.noworkflow'

It happens when the CheckReviewTask runs on an collection that used to have a workflow attached to it, but no longer does 

**Expected behavior**
the language string should say 'No workflow associated with this item'

**Stacktrace**
`java.lang.Error 
    	at com.tle.common.i18n.CurrentLocale$AbstractCurrentLocale.get(CurrentLocale.java:148) 
    	at com.tle.common.i18n.CurrentLocale.get(CurrentLocale.java:54) 
    	at com.tle.core.item.standard.operations.workflow.ReviewOperation.execute(ReviewOperation.java:61) 
    	at com.tle.core.item.service.impl.ItemServiceImpl.execute(ItemServiceImpl.java:998) 
    	at com.tle.core.item.service.impl.ItemServiceImpl.execute(ItemServiceImpl.java:949) 
    	at com.tle.core.item.service.impl.ItemServiceImpl.runOperation(ItemServiceImpl.java:817) 
    	at com.tle.core.item.service.impl.ItemServiceImpl$$EnhancerByGuice$$90d5bb2b.CGLIB$runOperation$6(<generated>) 
    	at com.tle.core.item.service.impl.ItemServiceImpl$$EnhancerByGuice$$90d5bb2b$$FastClassByGuice$$e2f159d3.invoke(<generated>) 
    	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228) 
    	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72) 
    	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106) 
    	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72) 
    	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106) 
    	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72) 
    	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52) 
    	at com.tle.core.item.service.impl.ItemServiceImpl$$EnhancerByGuice$$90d5bb2b.runOperation(<generated>) 
    	at com.tle.core.item.service.impl.ItemServiceImpl.processItemId(ItemServiceImpl.java:708) 
    	at com.tle.core.item.service.impl.ItemServiceImpl.operateAllPrivate(ItemServiceImpl.java:688) 
    	at com.tle.core.item.service.impl.ItemServiceImpl.operateAll(ItemServiceImpl.java:653) 
    	at com.tle.core.item.service.impl.ItemServiceImpl$$EnhancerByGuice$$90d5bb2b.CGLIB$operateAll$55(<generated>) 
    	at com.tle.core.item.service.impl.ItemServiceImpl$$EnhancerByGuice$$90d5bb2b$$FastClassByGuice$$e2f159d3.invoke(<generated>) 
    	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228) 
    	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72) 
    	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106) 
    	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72) 
    	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106) 
    	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72) 
    	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52) 
    	at com.tle.core.item.service.impl.ItemServiceImpl$$EnhancerByGuice$$90d5bb2b.operateAll(<generated>) 
    	at com.tle.core.item.standard.task.CheckReviewTask.execute(CheckReviewTask.java:43) 
    	at com.tle.core.scheduler.impl.SchedulerServiceImpl$2$1.call(SchedulerServiceImpl.java:489) 
    	at com.tle.core.scheduler.impl.SchedulerServiceImpl$2$1.call(SchedulerServiceImpl.java:485) 
    	at com.tle.core.institution.impl.RunAsInstitutionImpl.execute(RunAsInstitutionImpl.java:70) 
    	at com.tle.core.institution.impl.RunAsInstitutionImpl.executeAsSystem(RunAsInstitutionImpl.java:87) 
    	at com.tle.core.scheduler.impl.SchedulerServiceImpl$2.runTask(SchedulerServiceImpl.java:484) 
    	at com.tle.core.services.impl.SingleShotTask.call(SingleShotTask.java:35) 
    	at com.tle.core.services.impl.SingleShotTask.call(SingleShotTask.java:24) 
    	at com.tle.core.services.impl.LocalTaskServiceImpl$LocalTask.run(LocalTaskServiceImpl.java:597) 
    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
    	at java.lang.Thread.run(Thread.java:745)`

**Platform:**

- OpenEquella Version: 2018.2, 2019.1

**Comment by cbeach47** [comment]
This is still happening on some client installs.  Reopening.
